### ISSUE TITLE
Array.find polyfill replacement

### ISSUE THREAD

**Issue by maciejsmolinski** [sobstel/golazon#1]
Congratulations @sobstel, the app is so lightweight! Feels great and works like there was no network requests!

The timeline shows clearly everything is pretty granular and there are no long-running tasks:

![](https://cloud.githubusercontent.com/assets/90652/20933225/b7670916-bbd7-11e6-9f5b-45ae472a6bb0.png)

There's one thing that could be slightly improved in order to make the code even more lightweight. Kind of "save a few lines of code" thing.

I noticed `find` is not natively supported on Android Native browsers which is probably why you decided to use https://github.com/sobstel/golazon/blob/master/app/array.find.coffee polyfill. I also noticed this polyfill does not stop on the first met element which is pretty similar to the proposed solution below - no improvements here. Here's how you can save a few lines:

```
`if (!Array.prototype.find) {
    Array.prototype.find = function () { return this.filter.apply(this, [].slice.call(arguments))[0]; }
  }
`
```

`filter` is widely supported, even Android Native browsers support it well.

Hope it helps!
Maciej

**Comment by sobstel** [comment]
Thanks for great feedback. Maybe you wish to do a PR for `Array.prototype.find`? ;-)

**Comment by maciejsmolinski** [comment]
Sure! PR [Array.prototype.find implemented using `filter`](https://github.com/sobstel/golazon/pull/2) created
