### ISSUE TITLE
Upgrade to 1.0

### ISSUE THREAD

**Issue by jorgebucaran** [sobstel/golazon#5]
Just a friendly reminder that [Hyperapp 1.0](https://hackernoon.com/introducing-hyperapp-1-0-dbf4229abfef) has officially hit the streets and this module is now using an older API. Time to upgrade! 👋 

See also: https://github.com/hyperapp/awesome/issues/18

**Comment by sobstel** [comment]
@JorgeBucaran Thanks a lot for letting me know (and I appreciate your time to let everyone know), but for now I'm not going to upgrade to 1.0 (I've spent lamost 2h and I'm still far from finishing + have on unresolved issue with router where it's not updating route component after fetching data...  I simply don't have more time  to invest at the moment, sorry).
